modLoader="javafml"
loaderVersion="[39,)"
license="MIT"
logoFile="enhancedcraft.png"

[[mods]]
    modId="enhancedcraft"
    version="${file.jarVersion}"
    displayName="Enhanced Craft"
    credits="angxd, Iceattack"
    authors="angxd"
    description="Enhance your Minecraft experience with many new ores, mobs, biomes, and items, blocks!"

[[dependencies.enhancedcraft]]
    modId="forge"
    mandatory=true
    versionRange="[39.0.19,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.enhancedcraft]]
    modId="terrablender"
    mandatory=true
    versionRange="[1.0.0.59,)"
    ordering="NONE"
    side="BOTH"