modLoader="javafml"
loaderVersion="[39,)"
license="MIT"

[[mods]]
    modId="enhancedcraft"
    version="${file.jarVersion}"
    displayName="Enhanced Craft"
    authors="Angxd"
    description='''
    -- Minecraft expansion mod --
    New biomes, ores, armor, weapons, and much more!
    '''

[[dependencies.enhancedcraft]]
    modId="forge"
    mandatory=true
    versionRange="[39.0.19,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.enhancedcraft]]
    modId="terrablender"
    mandatory=true
    versionRange="[1.0.0.59,)"
    ordering="NONE"
    side="BOTH"